### ISSUE TITLE
It's not clear what the value of the asset_host configuration option should be.

### ISSUE THREAD

**Issue by ammar** [steveklabnik/emoji#24]
It was not clear whether `asset_host` should be set to the hostname only (example.com) or if it should also include the scheme (https://example.com). The example given in the README does not include the scheme, which suggested that it only takes a hostname:

```ruby
Emoji.asset_host = "emoji.cdn.com"
```

However, this results in the following output _(note the leading forward slash in src)_:
```
<img src="/emoji.cdn.com/emoji/heart.png" />
```
Instead of:
```
<img src="http://emoji.cdn.com/emoji/heart.png" />
```

Perhaps the name of the option should be `asset_base_url`? Or, if it's possible, prepend the value of `asset_host` with what ever scheme the app is using?

Otherwise a handy little gem, and the casbah, it rocks.

**Comment by wpeterson** [comment]
I added some code to handle all the weird edge cases for asset_host that make sense here, which should solve this bug and some other corner cases around it.

83c22e29a663a2412cf9dfc30557ed04b5ccfc6f
